<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Certificates are issued as a standalone printable HTML page (not a
 * generated PDF file) reached via a unique, unguessable token — the
 * test-taker uses the browser's "Print → Save as PDF" for a PDF copy.
 * This avoids adding a PDF-generation library as a dependency while still
 * giving instructors something they can hand out and verify.
 */
class QFA_Certificates {

	public static function init() {
		add_action( 'add_meta_boxes', array( __CLASS__, 'meta_box' ) );
		add_action( 'save_post_qmc_quiz', array( __CLASS__, 'save_settings' ) );
		add_action( 'wp_ajax_qmc_view_certificate', array( __CLASS__, 'render_certificate_page' ) );
		add_action( 'wp_ajax_nopriv_qmc_view_certificate', array( __CLASS__, 'render_certificate_page' ) );
	}

	public static function is_enabled( $quiz_id ) {
		return (bool) get_post_meta( $quiz_id, '_qmc_certificate_enabled', true );
	}

	/* ------------------------------------------------------------------ *
	 *  Admin UI
	 * ------------------------------------------------------------------ */

	public static function meta_box() {
		add_meta_box( 'qmc_certificate', __( 'Certificate', 'quizzis-for-all' ), array( __CLASS__, 'render_settings' ), 'qmc_quiz', 'side', 'default' );
	}

	public static function render_settings( $post ) {
		wp_nonce_field( 'qmc_save_certificate', 'qmc_certificate_nonce' );
		$enabled     = get_post_meta( $post->ID, '_qmc_certificate_enabled', true );
		$title       = get_post_meta( $post->ID, '_qmc_certificate_title', true ) ?: __( 'Certificate of Completion', 'quizzis-for-all' );
		$signee      = get_post_meta( $post->ID, '_qmc_certificate_signee', true );
		?>
		<p><label><input type="checkbox" name="qmc_certificate_enabled" <?php checked( $enabled, 1 ); ?>> <?php esc_html_e( 'Issue a certificate when a test-taker passes', 'quizzis-for-all' ); ?></label></p>
		<p><label><?php esc_html_e( 'Certificate title', 'quizzis-for-all' ); ?><br>
		<input type="text" name="qmc_certificate_title" style="width:100%;" value="<?php echo esc_attr( $title ); ?>"></label></p>
		<p><label><?php esc_html_e( 'Signed by (e.g. instructor name / title)', 'quizzis-for-all' ); ?><br>
		<input type="text" name="qmc_certificate_signee" style="width:100%;" value="<?php echo esc_attr( $signee ); ?>"></label></p>
		<?php
	}

	public static function save_settings( $post_id ) {
		if ( ! isset( $_POST['qmc_certificate_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['qmc_certificate_nonce'] ) ), 'qmc_save_certificate' ) ) {
			return;
		}
		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}
		update_post_meta( $post_id, '_qmc_certificate_enabled', ! empty( $_POST['qmc_certificate_enabled'] ) ? 1 : 0 );
		update_post_meta( $post_id, '_qmc_certificate_title', sanitize_text_field( wp_unslash( $_POST['qmc_certificate_title'] ?? '' ) ) );
		update_post_meta( $post_id, '_qmc_certificate_signee', sanitize_text_field( wp_unslash( $_POST['qmc_certificate_signee'] ?? '' ) ) );
	}

	/* ------------------------------------------------------------------ *
	 *  Issuing + rendering
	 * ------------------------------------------------------------------ */

	/**
	 * If certificates are enabled for this quiz and the attempt passed,
	 * generate a token, store it on the attempt, and return the public
	 * certificate URL. Returns '' otherwise.
	 */
	public static function maybe_issue( $quiz_id, $attempt_id, $passed ) {
		if ( ! $passed || ! self::is_enabled( $quiz_id ) || ! $attempt_id ) {
			return '';
		}
		$token = wp_generate_password( 32, false );
		QFA_DB::set_certificate_token( $attempt_id, $token );
		return add_query_arg(
			array(
				'action' => 'qmc_view_certificate',
				'token'  => $token,
			),
			admin_url( 'admin-ajax.php' )
		);
	}

	public static function render_certificate_page() {
		// Public certificate view: authentication here is the unguessable
		// 32-character token itself (generated by wp_generate_password and
		// matched against the attempts table), not a nonce — the link must
		// keep working from emails and bookmarks long after any nonce
		// would have expired. This is a read-only lookup; nothing changes.
		$token   = isset( $_GET['token'] ) ? sanitize_text_field( wp_unslash( $_GET['token'] ) ) : ''; // phpcs:ignore WordPress.Security.NonceVerification.Recommended
		$attempt = $token ? QFA_DB::get_attempt_by_certificate_token( $token ) : null;

		if ( ! $attempt ) {
			wp_die( esc_html__( 'Certificate not found.', 'quizzis-for-all' ) );
		}

		$quiz_title = get_the_title( $attempt->quiz_id );
		$cert_title = get_post_meta( $attempt->quiz_id, '_qmc_certificate_title', true ) ?: __( 'Certificate of Completion', 'quizzis-for-all' );
		$signee     = get_post_meta( $attempt->quiz_id, '_qmc_certificate_signee', true );
		$name       = $attempt->user_id ? get_the_author_meta( 'display_name', $attempt->user_id ) : ( $attempt->guest_name ?: __( 'Participant', 'quizzis-for-all' ) );
		$date       = mysql2date( get_option( 'date_format' ), $attempt->completed_at );

		nocache_headers();
		?>
		<!DOCTYPE html>
		<html <?php language_attributes(); ?>>
		<head>
			<meta charset="<?php bloginfo( 'charset' ); ?>">
			<title><?php echo esc_html( $cert_title . ' — ' . $name ); ?></title>
			<style>
				body { font-family: Georgia, 'Times New Roman', serif; background: #f4f4f4; margin: 0; padding: 40px; }
				.cert { max-width: 800px; margin: 0 auto; background: #fff; padding: 60px; border: 10px solid #2271b1; text-align: center; position: relative; }
				.cert::before { content: ""; position: absolute; inset: 14px; border: 2px solid #c9a227; pointer-events: none; }
				.cert h1 { font-size: 14px; letter-spacing: 4px; text-transform: uppercase; color: #888; margin-bottom: 30px; }
				.cert h2 { font-size: 40px; margin: 0 0 10px; color: #2271b1; }
				.cert .name { font-size: 30px; margin: 30px 0; border-bottom: 2px solid #ccc; display: inline-block; padding-bottom: 10px; }
				.cert .meta { color: #555; margin: 20px 0; }
				.cert .score { font-size: 20px; margin: 20px 0; }
				.cert .signee { margin-top: 50px; font-style: italic; }
				.print-btn { display: block; margin: 20px auto 0; text-align: center; }
				.print-btn button { background: #2271b1; color: #fff; border: none; padding: 10px 24px; border-radius: 4px; font-size: 15px; cursor: pointer; }
				@media print { .print-btn { display: none; } body { background: #fff; padding: 0; } .cert { border-width: 6px; } }
			</style>
		</head>
		<body>
			<div class="cert">
				<h1><?php bloginfo( 'name' ); ?></h1>
				<h2><?php echo esc_html( $cert_title ); ?></h2>
				<p><?php esc_html_e( 'This certifies that', 'quizzis-for-all' ); ?></p>
				<div class="name"><?php echo esc_html( $name ); ?></div>
				<p class="meta">
					<?php
					/* translators: %s: quiz title */
					printf( esc_html__( 'has successfully completed %s', 'quizzis-for-all' ), '<strong>' . esc_html( $quiz_title ) . '</strong>' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- the only unescaped part is our own literal <strong> markup; $quiz_title is escaped.
					?>
				</p>
				<p class="score">
					<?php
					/* translators: %s: percentage score, e.g. "82" */
					printf( esc_html__( 'Score: %s%%', 'quizzis-for-all' ), esc_html( $attempt->percentage ) );
					?>
				</p>
				<p class="meta"><?php echo esc_html( $date ); ?></p>
				<?php if ( $signee ) : ?>
					<p class="signee">— <?php echo esc_html( $signee ); ?></p>
				<?php endif; ?>
			</div>
			<div class="print-btn"><button onclick="window.print()"><?php esc_html_e( 'Print / Save as PDF', 'quizzis-for-all' ); ?></button></div>
		</body>
		</html>
		<?php
		exit;
	}
}
